In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Fake_Real_Data.csv")
df.head()

                                                Text label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1  U.S. conservative leader optimistic of common ...  Real
2  Trump proposes U.S. tax overhaul, stirs concer...  Real
3   Court Forces Ohio To Allow Millions Of Illega...  Fake
4  Democrats say Trump agrees to work on immigrat...  Real

In [3]:
df.shape

(9900, 2)

In [4]:
df.label.value_counts()
# to check any class imbalance

label
Fake    5000
Real    4900
Name: count, dtype: int64

In [6]:
df['new_label']=df['label'].map({"Fake":0,"Real":1})
df.head()

                                                Text label  new_label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake          0
1  U.S. conservative leader optimistic of common ...  Real          1
2  Trump proposes U.S. tax overhaul, stirs concer...  Real          1
3   Court Forces Ohio To Allow Millions Of Illega...  Fake          0
4  Democrats say Trump agrees to work on immigrat...  Real          1

In [8]:
import spacy

nlp=spacy.load("en_core_web_lg")

In [9]:
df["vector"]=df['Text'].apply(lambda text:nlp(text).vector)
df.head()
# it takes atleast 15 minutes to run

,Text,label,new_label,vector
0,Top Trump Surrogate BRUTALLY Stabs Him In The...,Fake,0,"[-0.6759837, 1.4263071, -2.318466, -0.451093, ..."
1,U.S. conservative leader optimistic of common ...,Real,1,"[-1.8355803, 1.3101058, -2.4919677, 1.0268308,..."
2,"Trump proposes U.S. tax overhaul, stirs concer...",Real,1,"[-1.9851209, 0.14389805, -2.4221718, 0.9133005..."
3,Court Forces Ohio To Allow Millions Of Illega...,Fake,0,"[-2.7812982, -0.16120885, -1.609772, 1.3624227..."
4,Democrats say Trump agrees to work on immigrat...,Real,1,"[-2.2010763, 0.9961637, -2.4088492, 1.128273, ..."

In [25]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(df.vector.values,df.new_label,test_size=.20,random_state=1)

In [26]:
x_train.shape

(7920,)

In [27]:
x_train[:2]

array([array([-1.94939792e+00,  7.88619697e-01, -2.02019882e+00,  1.10898018e+00,
               5.03301430e+00,  5.52429497e-01,  8.01890120e-02,  3.83396053e+00,
              -1.88193306e-01, -1.58970165e+00,  5.90676689e+00,  2.05990887e+00,
              -4.11033249e+00,  1.06999302e+00, -7.73379058e-02,  2.65125060e+00,
               1.22949922e+00, -1.36941418e-01, -1.67184663e+00, -1.95745707e+00,
               1.28660834e+00, -1.11873901e+00, -7.10126579e-01,  2.61898220e-01,
               5.75642049e-01, -1.32311666e+00, -2.19452500e+00, -7.26718366e-01,
              -5.46036720e-01,  6.91922724e-01,  9.12768066e-01,  7.65480772e-02,
              -5.80369532e-01, -1.98908150e+00, -2.69842386e+00, -1.31743729e+00,
              -4.44450587e-01,  9.84094203e-01,  4.45326030e-01,  2.17304781e-01,
               8.55333805e-01, -2.02002041e-02,  2.57786900e-01,  1.41474500e-01,
              -1.81422806e+00,  9.67741251e-01,  1.18776715e+00, -1.83999586e+00,
              -8.03420782e-01,  1.90711606e+00, -1.57298791e+00,  2.11178732e+00,
              -2.42780387e-01, -5.17231417e+00, -6.74309671e-01,  9.63724911e-01,
              -9.47907865e-02,  1.19750166e+00,  6.82264507e-01, -3.57032716e-01,
               9.56078768e-02, -1.54889202e+00,  1.91811085e-01, -1.15372777e+00,
               3.44055223e+00,  1.55114400e+00, -2.47654748e+00, -2.57608604e+00,
               7.16320634e-01,  2.24312663e+00, -4.24517363e-01, -8.74614418e-01,
              -2.15996122e+00,  5.30016363e-01, -4.50602919e-01,  1.38095438e+00,
              -2.45061684e+00,  2.53376436e+00, -3.49726939e+00, -2.95954794e-01,
              -4.20274353e+00, -4.16059315e-01,  8.25417936e-01,  1.97250259e+00,
               1.80570030e+00, -6.15672059e-02, -2.45670509e+00, -3.32427740e+00,
               1.30244434e+00, -7.13777244e-01, -9.88762498e-01,  5.73746622e-01,
               1.62715316e+00, -3.30307245e+00,  1.59887791e+00, -3.25229615e-01,
               9.11587656e-01, -1.06038129e+00,  7.51706064e-01,  2.49844050e+00,
               2.60383892e+00,  1.21797502e+00,  2.81655192e+00,  3.31304526e+00,
               2.24512562e-01,  4.23048878e+00,  1.36242974e+00, -2.94345856e+00,
              -5.44727266e-01, -4.35914087e+00,  1.57164991e+00,  7.54818082e-01,
              -2.17475176e+00,  8.30282390e-01,  1.18220210e+00,  6.10043108e-01,
              -4.25951391e-01, -7.60423303e-01, -1.90877495e-03, -1.13811541e+00,
              -5.23650050e-01, -3.36425614e+00,  1.16612732e+00,  2.79155463e-01,
              -5.72844028e-01, -3.06494689e+00,  1.48031068e+00, -2.24062347e+00,
               2.39598656e+00, -1.59583986e+00, -3.12908745e+00, -4.16414917e-01,
               3.97384763e+00, -3.38734575e-02,  1.15644440e-01,  5.87266386e-01,
              -2.06739330e+00, -1.59664288e-01,  2.07559514e+00, -1.92003405e+00,
              -2.09531760e+00, -1.40041769e+00,  2.63293162e-02,  1.11662161e+00,
               1.47256613e+00,  1.57875621e+00, -4.03771257e+00,  6.75848860e-04,
               1.24028194e+00,  1.09491277e+00, -8.56890559e-01,  3.22634029e+00,
              -3.48572075e-01,  1.48581851e+00, -1.65675259e+00,  1.11998963e+00,
               2.36456513e+00, -1.34475911e+00, -2.75345349e+00, -1.30348241e+00,
              -4.52506453e-01, -2.64247489e+00, -1.97434008e-01,  2.22710872e+00,
              -2.31497669e+00, -1.47538257e+00, -4.43056345e+00,  1.20237339e+00,
               7.03224897e-01, -1.69660479e-01,  8.34950089e-01, -1.74068421e-01,
               1.78964627e+00,  4.71352339e-01,  1.45117486e+00,  6.70933008e-01,
               6.16850704e-02, -6.80680156e-01, -2.70924449e+00, -1.35548103e+00,
              -9.48352993e-01,  2.07909271e-01,  7.74443150e-01,  2.85373330e-01,
              -1.13207686e+00,  1.31135178e+00, -1.51479125e+00,  3.62449318e-01,
               1.14311039e+00,  1.61060548e+00,  4.17817354e-01, -1.71818280e+00,
              -1.39518395e-01, -1.78416312e+00, -2.92608351e-01,  9.95122910e-01,
              -2.92350435e+00, -7.69406319e-01, -5.11712015e-01,  9.65267599e-01,
              -1.74680269e+00, -1.71672952e+00,  4.24229443e-01, -2.40657187e+00,
               3.56604314e+00,  7.98448741e-01, -3.49688101e+00,  2.12404847e+00,
               2.03873560e-01, -1.96146250e-01,  1.48081958e+00,  9.36639249e-01,
              -1.57537949e+00,  1.55618751e+00,  1.25486541e+00,  2.40701580e+00,
               9.45770860e-01, -2.74491739e+00, -5.68433478e-02,  2.37314794e-02,
              -2.41055751e+00,  1.40432346e+00, -4.61149693e-01,  1.49893677e-02,
              -2.39042115e+00, -1.66574812e+00,  4.12764817e-01,  3.11880302e+00,
               5.47524810e-01,  1.71393529e-01,  3.38371921e+00, -2.51919222e+00,
              -1.18624794e+00,  1.88710845e+00,  2.95271683e+00,  1.35098577e+00,
              -1.57852840e+00,  2.16817304e-01, -4.01360095e-01, -5.85252881e-01,
              -5.35667777e-01,  4.89159346e-01,  1.58811915e+00,  1.80598106e-02,
              -1.64115095e+00,  2.36343408e+00, -2.39440894e+00, -7.45577225e-03,
              -8.03881064e-02,  2.69297886e+00,  1.18216574e+00, -2.97448397e+00,
              -4.69458437e+00, -6.93155468e-01,  1.11698568e+00, -2.62967610e+00,
               1.93454599e+00, -1.22657025e+00,  3.33938330e-01,  1.24046397e+00,
              -8.12515259e-01,  5.14663744e+00,  3.01083803e+00,  2.47990847e+00,
               2.20816803e+00, -5.42900801e-01,  1.02401935e-01,  2.14700937e+00,
              -3.13696575e+00, -2.30523735e-01, -3.11855882e-01, -8.13998505e-02,
               1.06178844e+00, -2.11689353e+00,  1.16857588e+00, -9.19633567e-01,
               1.20513701e+00, -2.45173931e+00, -9.01040494e-01,  1.70295620e+00,
               1.76059580e+00,  4.47154999e-01,  8.10685635e-01,  9.86511886e-01,
               2.17892957e+00, -5.36153197e-01,  5.54539621e-01,  1.77447450e+00,
              -1.02465165e+00,  4.27913517e-01,  6.78758860e-01, -7.56293654e-01,
              -1.51115024e+00,  6.15855038e-01, -1.46339917e+00,  1.56232834e+00,
               7.95694947e-01, -1.33923340e+00, -1.97332442e+00,  9.01919842e-01],
             dtype=float32)                                                       ,
       array([-1.74393976e+00,  1.10287642e+00, -1.96445465e+00,  4.96553749e-01,
               3.45086646e+00,  5.69631696e-01,  1.56121224e-01,  4.57204866e+00,
              -3.01603347e-01, -6.01760447e-01,  5.65478039e+00,  1.19534576e+00,
              -3.13373423e+00,  6.02333963e-01,  7.99938142e-01,  1.94468868e+00,
               5.48769593e-01, -4.87347156e-01, -1.76204312e+00, -1.42305911e+00,
               9.22622919e-01, -4.63093072e-01, -1.11288643e+00, -4.43361014e-01,
               7.09369406e-02, -1.84581375e+00, -2.33546877e+00, -8.97644222e-01,
              -6.39006197e-01,  1.04694116e+00,  9.54618812e-01, -2.37046584e-01,
              -1.13277733e+00, -1.33516312e+00, -2.75944161e+00, -7.55082786e-01,
              -8.53296518e-01,  1.12694383e+00,  6.67561591e-01,  6.45821869e-01,
              -7.82356858e-02,  2.78087974e-01, -9.45459381e-02,  3.56029212e-01,
              -1.28487408e+00,  1.46839678e+00,  2.55015731e-01, -2.96141577e+00,
              -8.91940713e-01,  2.39511180e+00, -1.58705699e+00,  1.57821357e+00,
               4.69374746e-01, -4.74295473e+00, -4.58914161e-01,  2.46194363e-01,
               3.24951798e-01,  7.64646113e-01,  8.18146467e-01, -2.88539350e-01,
               6.60832524e-01, -1.28257060e+00,  1.37621865e-01, -1.86431348e+00,
               2.44759631e+00,  1.44975865e+00, -2.42682147e+00, -2.78608346e+00,
               1.17519963e+00,  2.16918445e+00, -3.40006202e-01, -2.23940417e-01,
              -1.49137390e+00, -2.34037712e-02, -9.86730214e-03,  1.35505617e+00,
              -3.64794683e+00,  2.44945908e+00, -3.16396809e+00, -1.90850243e-01,
              -3.54584980e+00, -2.35928539e-02,  1.09145033e+00,  7.48550832e-01,
               2.41564322e+00,  2.88761824e-01, -2.38277411e+00, -2.68782330e+00,
               1.27585018e+00, -8.84804726e-01, -9.82453823e-01, -8.59129727e-01,
               2.08979487e+00, -3.55111647e+00,  8.29248846e-01, -1.27392995e+00,
               2.72416115e-01, -8.34501386e-01,  1.55329275e+00,  1.44114637e+00,
               2.39592004e+00,  1.37755871e+00,  2.04710221e+00,  2.93656278e+00,
              -1.01912165e+00,  3.36961722e+00, -1.53797448e-01, -1.94970047e+00,
              -2.45051324e-01, -3.05729532e+00,  8.03267658e-01,  5.50453544e-01,
              -1.16262782e+00,  9.58848417e-01,  1.07168043e+00,  7.65541613e-01,
              -9.44927394e-01, -2.54387152e-03, -3.99342656e-01, -3.55768621e-01,
              -8.86692286e-01, -2.89382029e+00,  3.06044728e-01,  1.13056946e+00,
              -1.14490247e+00, -3.39494920e+00,  1.35140312e+00, -1.64739990e+00,
               2.39158082e+00, -1.39530528e+00, -2.26072931e+00, -1.92199990e-01,
               3.83168125e+00, -5.36256969e-01, -2.98938215e-01,  1.12207806e+00,
              -2.00763965e+00, -7.69626319e-01,  3.10824370e+00, -1.66298950e+00,
              -2.51528645e+00, -1.03765118e+00,  7.03843594e-01,  1.87097144e+00,
               7.09448457e-01,  1.27719492e-01, -3.85231113e+00, -2.17422619e-01,
               9.34811473e-01,  3.49263072e-01,  5.47603548e-01,  1.77661681e+00,
              -1.58552259e-01,  1.75260985e+00, -1.94687676e+00,  1.01239800e+00,
               2.41085291e+00, -8.64428878e-01, -2.25904655e+00, -1.43578243e+00,
              -8.08278561e-01, -2.96900225e+00, -5.52796960e-01,  1.93828881e+00,
              -2.56909394e+00, -1.78489065e+00, -3.46185780e+00,  8.37171078e-01,
              -7.56634176e-01,  2.89897323e-01,  1.30561805e+00, -1.80191904e-01,
               1.97703052e+00,  6.58236921e-01,  2.09586620e+00, -2.92378932e-01,
              -3.21381986e-01,  1.08957335e-01, -2.24448061e+00, -1.41358781e+00,
              -1.21700191e+00,  1.21664989e-03,  1.55963194e+00,  2.14482561e-01,
              -1.19352436e+00,  7.91752279e-01, -1.18643081e+00, -2.16800675e-01,
               1.60099924e+00,  2.22151232e+00, -2.24084407e-01, -1.39690697e+00,
              -2.17696577e-02, -4.82235610e-01, -1.10380329e-01,  2.25230008e-01,
              -2.84974217e+00,  1.58482745e-01,  1.71804398e-01,  1.15467370e+00,
              -1.02408016e+00, -1.29863703e+00, -2.18873248e-01, -1.70999539e+00,
               2.46494341e+00,  9.43587184e-01, -3.19892931e+00,  1.06639314e+00,
              -6.06744647e-01, -7.33243525e-01,  1.12664258e+00,  8.36606264e-01,
              -1.20284593e+00,  2.31627893e+00,  4.82260317e-01,  2.67258716e+00,
               2.96879619e-01, -2.06802225e+00, -4.46710624e-02,  5.37703991e-01,
              -1.79808331e+00,  1.40603971e+00, -1.51473209e-01,  7.33785748e-01,
              -1.85996330e+00, -7.45425403e-01,  5.73683083e-01,  2.67379618e+00,
               1.38920975e+00,  3.49422991e-01,  2.25510359e+00, -2.15266705e+00,
              -3.61859679e-01,  1.81969380e+00,  1.54371130e+00,  1.22233665e+00,
              -1.72944975e+00,  4.43854839e-01, -8.85636032e-01, -7.51570642e-01,
              -9.58929658e-01,  1.21637142e+00,  1.97586930e+00,  2.39064679e-01,
              -1.06181002e+00,  1.00409079e+00, -1.99737728e+00,  1.92147672e-01,
               7.57640421e-01,  2.72609615e+00,  5.84078610e-01, -2.09285212e+00,
              -5.13007784e+00, -2.69596636e-01,  5.18538475e-01, -2.02653837e+00,
               1.69961917e+00, -1.50399894e-01, -1.73021127e-02,  1.22934270e+00,
              -6.68781903e-03,  3.82471848e+00,  3.00016904e+00,  2.24668717e+00,
               1.55829358e+00, -3.93531442e-01,  2.70226747e-01,  2.61074519e+00,
              -3.52603984e+00,  1.06525682e-01,  7.40650654e-01, -5.90854883e-01,
               3.85837376e-01, -1.87427163e+00,  6.40478611e-01, -6.84976161e-01,
               1.45528913e+00, -1.51611733e+00, -1.29468858e+00,  1.95979500e+00,
               9.96742487e-01,  8.19305405e-02,  9.93157148e-01,  7.67264783e-01,
               2.97062993e+00, -8.56171370e-01,  4.16843772e-01,  1.94502676e+00,
              -1.37801242e+00, -2.97217548e-01,  9.78711784e-01, -9.86437023e-01,
               5.15839458e-02, -4.99990255e-01, -1.18415940e+00,  1.22688913e+00,
               9.18629825e-01, -1.00215673e+00, -2.70196509e+00,  1.29512095e+00],
             dtype=float32)                                                       ],
      dtype=object)

In [28]:
import numpy as np

In [29]:
x_train=np.stack(x_train)
x_train[:2]
# to convert it into 2d array

array([[-1.94939792e+00,  7.88619697e-01, -2.02019882e+00,
         1.10898018e+00,  5.03301430e+00,  5.52429497e-01,
         8.01890120e-02,  3.83396053e+00, -1.88193306e-01,
        -1.58970165e+00,  5.90676689e+00,  2.05990887e+00,
        -4.11033249e+00,  1.06999302e+00, -7.73379058e-02,
         2.65125060e+00,  1.22949922e+00, -1.36941418e-01,
        -1.67184663e+00, -1.95745707e+00,  1.28660834e+00,
        -1.11873901e+00, -7.10126579e-01,  2.61898220e-01,
         5.75642049e-01, -1.32311666e+00, -2.19452500e+00,
        -7.26718366e-01, -5.46036720e-01,  6.91922724e-01,
         9.12768066e-01,  7.65480772e-02, -5.80369532e-01,
        -1.98908150e+00, -2.69842386e+00, -1.31743729e+00,
        -4.44450587e-01,  9.84094203e-01,  4.45326030e-01,
         2.17304781e-01,  8.55333805e-01, -2.02002041e-02,
         2.57786900e-01,  1.41474500e-01, -1.81422806e+00,
         9.67741251e-01,  1.18776715e+00, -1.83999586e+00,
        -8.03420782e-01,  1.90711606e+00, -1.57298791e+00,
         2.11178732e+00, -2.42780387e-01, -5.17231417e+00,
        -6.74309671e-01,  9.63724911e-01, -9.47907865e-02,
         1.19750166e+00,  6.82264507e-01, -3.57032716e-01,
         9.56078768e-02, -1.54889202e+00,  1.91811085e-01,
        -1.15372777e+00,  3.44055223e+00,  1.55114400e+00,
        -2.47654748e+00, -2.57608604e+00,  7.16320634e-01,
         2.24312663e+00, -4.24517363e-01, -8.74614418e-01,
        -2.15996122e+00,  5.30016363e-01, -4.50602919e-01,
         1.38095438e+00, -2.45061684e+00,  2.53376436e+00,
        -3.49726939e+00, -2.95954794e-01, -4.20274353e+00,
        -4.16059315e-01,  8.25417936e-01,  1.97250259e+00,
         1.80570030e+00, -6.15672059e-02, -2.45670509e+00,
        -3.32427740e+00,  1.30244434e+00, -7.13777244e-01,
        -9.88762498e-01,  5.73746622e-01,  1.62715316e+00,
        -3.30307245e+00,  1.59887791e+00, -3.25229615e-01,
         9.11587656e-01, -1.06038129e+00,  7.51706064e-01,
         2.49844050e+00,  2.60383892e+00,  1.21797502e+00,
         2.81655192e+00,  3.31304526e+00,  2.24512562e-01,
         4.23048878e+00,  1.36242974e+00, -2.94345856e+00,
        -5.44727266e-01, -4.35914087e+00,  1.57164991e+00,
         7.54818082e-01, -2.17475176e+00,  8.30282390e-01,
         1.18220210e+00,  6.10043108e-01, -4.25951391e-01,
        -7.60423303e-01, -1.90877495e-03, -1.13811541e+00,
        -5.23650050e-01, -3.36425614e+00,  1.16612732e+00,
         2.79155463e-01, -5.72844028e-01, -3.06494689e+00,
         1.48031068e+00, -2.24062347e+00,  2.39598656e+00,
        -1.59583986e+00, -3.12908745e+00, -4.16414917e-01,
         3.97384763e+00, -3.38734575e-02,  1.15644440e-01,
         5.87266386e-01, -2.06739330e+00, -1.59664288e-01,
         2.07559514e+00, -1.92003405e+00, -2.09531760e+00,
        -1.40041769e+00,  2.63293162e-02,  1.11662161e+00,
         1.47256613e+00,  1.57875621e+00, -4.03771257e+00,
         6.75848860e-04,  1.24028194e+00,  1.09491277e+00,
        -8.56890559e-01,  3.22634029e+00, -3.48572075e-01,
         1.48581851e+00, -1.65675259e+00,  1.11998963e+00,
         2.36456513e+00, -1.34475911e+00, -2.75345349e+00,
        -1.30348241e+00, -4.52506453e-01, -2.64247489e+00,
        -1.97434008e-01,  2.22710872e+00, -2.31497669e+00,
        -1.47538257e+00, -4.43056345e+00,  1.20237339e+00,
         7.03224897e-01, -1.69660479e-01,  8.34950089e-01,
        -1.74068421e-01,  1.78964627e+00,  4.71352339e-01,
         1.45117486e+00,  6.70933008e-01,  6.16850704e-02,
        -6.80680156e-01, -2.70924449e+00, -1.35548103e+00,
        -9.48352993e-01,  2.07909271e-01,  7.74443150e-01,
         2.85373330e-01, -1.13207686e+00,  1.31135178e+00,
        -1.51479125e+00,  3.62449318e-01,  1.14311039e+00,
         1.61060548e+00,  4.17817354e-01, -1.71818280e+00,
        -1.39518395e-01, -1.78416312e+00, -2.92608351e-01,
         9.95122910e-01, -2.92350435e+00, -7.69406319e-01,
        -5.11712015e-01,  9.65267599e-01, -1.74680269e+00,
        -1.71672952e+00,  4.24229443e-01, -2.40657187e+00,
         3.56604314e+00,  7.98448741e-01, -3.49688101e+00,
         2.12404847e+00,  2.03873560e-01, -1.96146250e-01,
         1.48081958e+00,  9.36639249e-01, -1.57537949e+00,
         1.55618751e+00,  1.25486541e+00,  2.40701580e+00,
         9.45770860e-01, -2.74491739e+00, -5.68433478e-02,
         2.37314794e-02, -2.41055751e+00,  1.40432346e+00,
        -4.61149693e-01,  1.49893677e-02, -2.39042115e+00,
        -1.66574812e+00,  4.12764817e-01,  3.11880302e+00,
         5.47524810e-01,  1.71393529e-01,  3.38371921e+00,
        -2.51919222e+00, -1.18624794e+00,  1.88710845e+00,
         2.95271683e+00,  1.35098577e+00, -1.57852840e+00,
         2.16817304e-01, -4.01360095e-01, -5.85252881e-01,
        -5.35667777e-01,  4.89159346e-01,  1.58811915e+00,
         1.80598106e-02, -1.64115095e+00,  2.36343408e+00,
        -2.39440894e+00, -7.45577225e-03, -8.03881064e-02,
         2.69297886e+00,  1.18216574e+00, -2.97448397e+00,
        -4.69458437e+00, -6.93155468e-01,  1.11698568e+00,
        -2.62967610e+00,  1.93454599e+00, -1.22657025e+00,
         3.33938330e-01,  1.24046397e+00, -8.12515259e-01,
         5.14663744e+00,  3.01083803e+00,  2.47990847e+00,
         2.20816803e+00, -5.42900801e-01,  1.02401935e-01,
         2.14700937e+00, -3.13696575e+00, -2.30523735e-01,
        -3.11855882e-01, -8.13998505e-02,  1.06178844e+00,
        -2.11689353e+00,  1.16857588e+00, -9.19633567e-01,
         1.20513701e+00, -2.45173931e+00, -9.01040494e-01,
         1.70295620e+00,  1.76059580e+00,  4.47154999e-01,
         8.10685635e-01,  9.86511886e-01,  2.17892957e+00,
        -5.36153197e-01,  5.54539621e-01,  1.77447450e+00,
        -1.02465165e+00,  4.27913517e-01,  6.78758860e-01,
        -7.56293654e-01, -1.51115024e+00,  6.15855038e-01,
        -1.46339917e+00,  1.56232834e+00,  7.95694947e-01,
        -1.33923340e+00, -1.97332442e+00,  9.01919842e-01],
       [-1.74393976e+00,  1.10287642e+00, -1.96445465e+00,
         4.96553749e-01,  3.45086646e+00,  5.69631696e-01,
         1.56121224e-01,  4.57204866e+00, -3.01603347e-01,
        -6.01760447e-01,  5.65478039e+00,  1.19534576e+00,
        -3.13373423e+00,  6.02333963e-01,  7.99938142e-01,
         1.94468868e+00,  5.48769593e-01, -4.87347156e-01,
        -1.76204312e+00, -1.42305911e+00,  9.22622919e-01,
        -4.63093072e-01, -1.11288643e+00, -4.43361014e-01,
         7.09369406e-02, -1.84581375e+00, -2.33546877e+00,
        -8.97644222e-01, -6.39006197e-01,  1.04694116e+00,
         9.54618812e-01, -2.37046584e-01, -1.13277733e+00,
        -1.33516312e+00, -2.75944161e+00, -7.55082786e-01,
        -8.53296518e-01,  1.12694383e+00,  6.67561591e-01,
         6.45821869e-01, -7.82356858e-02,  2.78087974e-01,
        -9.45459381e-02,  3.56029212e-01, -1.28487408e+00,
         1.46839678e+00,  2.55015731e-01, -2.96141577e+00,
        -8.91940713e-01,  2.39511180e+00, -1.58705699e+00,
         1.57821357e+00,  4.69374746e-01, -4.74295473e+00,
        -4.58914161e-01,  2.46194363e-01,  3.24951798e-01,
         7.64646113e-01,  8.18146467e-01, -2.88539350e-01,
         6.60832524e-01, -1.28257060e+00,  1.37621865e-01,
        -1.86431348e+00,  2.44759631e+00,  1.44975865e+00,
        -2.42682147e+00, -2.78608346e+00,  1.17519963e+00,
         2.16918445e+00, -3.40006202e-01, -2.23940417e-01,
        -1.49137390e+00, -2.34037712e-02, -9.86730214e-03,
         1.35505617e+00, -3.64794683e+00,  2.44945908e+00,
        -3.16396809e+00, -1.90850243e-01, -3.54584980e+00,
        -2.35928539e-02,  1.09145033e+00,  7.48550832e-01,
         2.41564322e+00,  2.88761824e-01, -2.38277411e+00,
        -2.68782330e+00,  1.27585018e+00, -8.84804726e-01,
        -9.82453823e-01, -8.59129727e-01,  2.08979487e+00,
        -3.55111647e+00,  8.29248846e-01, -1.27392995e+00,
         2.72416115e-01, -8.34501386e-01,  1.55329275e+00,
         1.44114637e+00,  2.39592004e+00,  1.37755871e+00,
         2.04710221e+00,  2.93656278e+00, -1.01912165e+00,
         3.36961722e+00, -1.53797448e-01, -1.94970047e+00,
        -2.45051324e-01, -3.05729532e+00,  8.03267658e-01,
         5.50453544e-01, -1.16262782e+00,  9.58848417e-01,
         1.07168043e+00,  7.65541613e-01, -9.44927394e-01,
        -2.54387152e-03, -3.99342656e-01, -3.55768621e-01,
        -8.86692286e-01, -2.89382029e+00,  3.06044728e-01,
         1.13056946e+00, -1.14490247e+00, -3.39494920e+00,
         1.35140312e+00, -1.64739990e+00,  2.39158082e+00,
        -1.39530528e+00, -2.26072931e+00, -1.92199990e-01,
         3.83168125e+00, -5.36256969e-01, -2.98938215e-01,
         1.12207806e+00, -2.00763965e+00, -7.69626319e-01,
         3.10824370e+00, -1.66298950e+00, -2.51528645e+00,
        -1.03765118e+00,  7.03843594e-01,  1.87097144e+00,
         7.09448457e-01,  1.27719492e-01, -3.85231113e+00,
        -2.17422619e-01,  9.34811473e-01,  3.49263072e-01,
         5.47603548e-01,  1.77661681e+00, -1.58552259e-01,
         1.75260985e+00, -1.94687676e+00,  1.01239800e+00,
         2.41085291e+00, -8.64428878e-01, -2.25904655e+00,
        -1.43578243e+00, -8.08278561e-01, -2.96900225e+00,
        -5.52796960e-01,  1.93828881e+00, -2.56909394e+00,
        -1.78489065e+00, -3.46185780e+00,  8.37171078e-01,
        -7.56634176e-01,  2.89897323e-01,  1.30561805e+00,
        -1.80191904e-01,  1.97703052e+00,  6.58236921e-01,
         2.09586620e+00, -2.92378932e-01, -3.21381986e-01,
         1.08957335e-01, -2.24448061e+00, -1.41358781e+00,
        -1.21700191e+00,  1.21664989e-03,  1.55963194e+00,
         2.14482561e-01, -1.19352436e+00,  7.91752279e-01,
        -1.18643081e+00, -2.16800675e-01,  1.60099924e+00,
         2.22151232e+00, -2.24084407e-01, -1.39690697e+00,
        -2.17696577e-02, -4.82235610e-01, -1.10380329e-01,
         2.25230008e-01, -2.84974217e+00,  1.58482745e-01,
         1.71804398e-01,  1.15467370e+00, -1.02408016e+00,
        -1.29863703e+00, -2.18873248e-01, -1.70999539e+00,
         2.46494341e+00,  9.43587184e-01, -3.19892931e+00,
         1.06639314e+00, -6.06744647e-01, -7.33243525e-01,
         1.12664258e+00,  8.36606264e-01, -1.20284593e+00,
         2.31627893e+00,  4.82260317e-01,  2.67258716e+00,
         2.96879619e-01, -2.06802225e+00, -4.46710624e-02,
         5.37703991e-01, -1.79808331e+00,  1.40603971e+00,
        -1.51473209e-01,  7.33785748e-01, -1.85996330e+00,
        -7.45425403e-01,  5.73683083e-01,  2.67379618e+00,
         1.38920975e+00,  3.49422991e-01,  2.25510359e+00,
        -2.15266705e+00, -3.61859679e-01,  1.81969380e+00,
         1.54371130e+00,  1.22233665e+00, -1.72944975e+00,
         4.43854839e-01, -8.85636032e-01, -7.51570642e-01,
        -9.58929658e-01,  1.21637142e+00,  1.97586930e+00,
         2.39064679e-01, -1.06181002e+00,  1.00409079e+00,
        -1.99737728e+00,  1.92147672e-01,  7.57640421e-01,
         2.72609615e+00,  5.84078610e-01, -2.09285212e+00,
        -5.13007784e+00, -2.69596636e-01,  5.18538475e-01,
        -2.02653837e+00,  1.69961917e+00, -1.50399894e-01,
        -1.73021127e-02,  1.22934270e+00, -6.68781903e-03,
         3.82471848e+00,  3.00016904e+00,  2.24668717e+00,
         1.55829358e+00, -3.93531442e-01,  2.70226747e-01,
         2.61074519e+00, -3.52603984e+00,  1.06525682e-01,
         7.40650654e-01, -5.90854883e-01,  3.85837376e-01,
        -1.87427163e+00,  6.40478611e-01, -6.84976161e-01,
         1.45528913e+00, -1.51611733e+00, -1.29468858e+00,
         1.95979500e+00,  9.96742487e-01,  8.19305405e-02,
         9.93157148e-01,  7.67264783e-01,  2.97062993e+00,
        -8.56171370e-01,  4.16843772e-01,  1.94502676e+00,
        -1.37801242e+00, -2.97217548e-01,  9.78711784e-01,
        -9.86437023e-01,  5.15839458e-02, -4.99990255e-01,
        -1.18415940e+00,  1.22688913e+00,  9.18629825e-01,
        -1.00215673e+00, -2.70196509e+00,  1.29512095e+00]], dtype=float32)

In [30]:
x_test=np.stack(x_test)

In [34]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [35]:
from sklearn.naive_bayes import MultinomialNB

model=MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB()

In [37]:
y_test[:5]

4322    0
8862    1
8024    0
260     1
6998    1
Name: new_label, dtype: int64

In [38]:
y_pred=model.predict(x_test)
y_pred[:5]

array([0, 1, 0, 1, 1], dtype=int64)

In [41]:
from sklearn.metrics import classification_report

In [42]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.94      0.95      1020
           1       0.94      0.96      0.95       960

    accuracy                           0.95      1980
   macro avg       0.95      0.95      0.95      1980
weighted avg       0.95      0.95      0.95      1980